ignores:
  - "**/SUMMARY.md"
  - CODE_OF_CONDUCT.md
  - "docs/**"
  - ".github/**"
  - README.md

noProgress: true

config:
  # Default state for all rules
  default: true

  # MD001/heading-increment/header-increment - Heading levels should only increment by one level at a time
  MD001: false

  # MD013/line-length - Line length
  MD013: false

  # MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
  MD024:
    # Allow different nesting
    allow_different_nesting: true
    # Only check sibling headings
    siblings_only: false

  # MD033/no-inline-html - Inline HTML
  MD033: false

  # MD034/no-bare-urls - Bare URL used
  MD034: false

  # MD036/no-emphasis-as-heading/no-emphasis-as-header - We need certain headings that aren't anchored
  MD036: false