import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
	`java-library`
	`maven-publish`
	kotlin("jvm") version "2.1.0"
}

repositories {
	mavenLocal()
	maven {
		url = uri("https://libraries.minecraft.net")
	}

	maven {
		url = uri("https://repo.papermc.io/repository/maven-public/")
	}

	maven {
		url = uri("https://repo.codemc.org/repository/maven-public/")
	}

	maven {
		url = uri("https://repo.maven.apache.org/maven2/")
	}

	maven {
		url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots")
	}
}

dependencies {
	api(libs.net.kyori.adventure.platform.bukkit)
	api(libs.com.github.seeseemelk.mockbukkit.v1.v20)
	api(libs.dev.jorel.commandapi.bukkit.test.toolkit)
	api(libs.org.junit.jupiter.junit.jupiter.engine)
	api(libs.dev.jorel.commandapi.bukkit.core)
	api(libs.dev.jorel.commandapi.bukkit.kotlin)
	api(libs.dev.jorel.commandapi.annotations)
	api(libs.de.tr7zw.item.nbt.api)
	api(libs.org.jetbrains.kotlin.kotlin.stdlib)
	compileOnly(libs.com.mojang.brigadier)
	compileOnly(libs.com.mojang.authlib)
	compileOnly(libs.io.papermc.paper.paper.api)
}

group = "dev.jorel"
version = "9.6.2-SNAPSHOT"
description = "commandapi-documentation-code"
java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21

java {
	withSourcesJar()
	withJavadocJar()
}

tasks.withType<JavaCompile>() {
	options.encoding = "UTF-8"
}

tasks.withType<KotlinCompile> {
	compilerOptions.jvmTarget = JvmTarget.JVM_21
}

tasks.withType<Javadoc>() {
	options.encoding = "UTF-8"
}
