name: build
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        java: [
          21,
        ]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the docs repository
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Run markdownlint on all documentation Markdown documents
        uses: DavidAnson/markdownlint-cli2-action@v8
        with:
          globs: 'docssrc/src/*.md'

      - name: Build commandapi-documentation-code
        run: cd commandapi-documentation-code && ./gradlew build
        
      - name: Build commandapi-documentation-velocity-code
        run: cd commandapi-documentation-velocity-code && ./gradlew build