name: build
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        java: [
          21,
        ]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the docs repository
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Run markdownlint on all documentation Markdown documents
        uses: DavidAnson/markdownlint-cli2-action@v8
        with:
          globs: 'docssrc/src/*.md'

      - name: Build the documentation with mdBook
        continue-on-error: true # If link checking fails with 403, that's probably just a timing/automated-related issue. We can ignore those - forcing the whole build to fail for this is not ideal.
        run: |
          cd docssrc
          curl -LJO https://github.com/JorelAli/mdBook/releases/download/v0.4.21-fa6/mdbook-fa6 && chmod +x mdbook-fa6
          mkdir -p mdbook-linkcheck && cd "$_" && curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip && unzip "$_" && chmod +x mdbook-linkcheck && export PATH=$PWD:$PATH && cd ..
          ./mdbook-fa6 build

      - name: Build commandapi-documentation-code
        run: cd commandapi-documentation-code && ./gradlew build

      - name: Build commandapi-documentation-velocity-code
        run: cd commandapi-documentation-velocity-code && ./gradlew build